server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${PSQL_HOST}:${PSQL_PORT}/${PSQL_NAME}
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASS}
    driver-class-name: org.postgresql.Driver
  
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

