server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: "http://${PSQL_HOST}:${PORT}/api/auth/google/callback"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://oauth2.googleapis.com/oauth2/v3/userinfo

  datasource:
    url: jdbc:postgresql://${PSQL_HOST}:${PSQL_PORT}/${PSQL_NAME}
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASS}
    driver-class-name: org.postgresql.Driver
  
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  accessTime: ${ACCESS_TIME}
  refreshTime: ${REFRESH_TIME}